Repository stadt-karlsruhe/open-data-dashboard, pull requests merged in 2024-05, with the labels that each got.

#26 docs: Set up MkDocs for application documentation
  .github/dependabot.yml
  .gitignore
  .readthedocs.yml
  .vscode/extensions.json
  .vscode/settings.json
  README.md
  docs/index.de.md
  docs/index.md
  docs/requirements.txt
  mkdocs.yml
  package.json
Labels: documentation, enhancement

#39 docs: Deploy documentation to Read the Docs
  .github/workflows/build-docs.yml
  .gitignore
  .readthedocs.yml
  README.md
  docs/index.en.md
  mkdocs.yml
Labels: documentation, enhancement

#48 feat: Read resources from config file instead of mock data
  src/app/resource/[resourceId]/page.tsx
  src/components/visualization/chart-table-filter/ChartTableFilter.tsx
  src/components/visualization/layout/ChartTableWrapper.tsx
  src/components/visualization/layout/Visualization.tsx
  src/data/mockData.ts
  src/transform.ts
  src/types/configuration.d.ts
  src/types/visualization.d.ts
Labels: enhancement

#56 feat: Refactor filter component and use react-bootstrap
  src/app/[locale]/layout.tsx
  src/components/LocaleSwitcher.tsx
  src/components/helper/BootstrapJS.tsx
  src/components/visualization/chart-table-filter/ChartTableFilter.tsx
  src/components/visualization/chart-table-filter/ChartTableFilterBody.tsx
  src/components/visualization/chart-table-filter/ChartTableFilterHead.tsx
  src/components/visualization/chart-table-filter/ChartTableFilterHeader.tsx
  src/components/visualization/chart-table-filter/ClearableInputGroup.tsx
  src/components/visualization/chart-table-filter/CurrentFilters.tsx
  src/components/visualization/chart-table-filter/FloatingLabelInput.tsx
  src/components/visualization/layout/ChartTableWrapper.tsx
  src/messages/de.json
  src/messages/en.json
  src/types/bootstrap.d.ts
Labels: enhancement

#32 feat: add tooltip to map markers, add reset button to map, add legend to map
  src/colors.ts
  src/components/visualization/Map.tsx
  src/components/visualization/layout/Visualization.tsx
  src/components/visualization/map/GeoMap.tsx
  src/components/visualization/map/Legend.tsx
  src/components/visualization/map/ResetView.tsx
  src/components/visualization/map/mapstyles.module.css
  src/messages/de.json
  src/messages/en.json
Labels: enhancement

#67 feat: Use Node.js instead of static export, configure test coverage
  .github/workflows/build-deploy.yml
  .github/workflows/lint-test.yml
  .vscode/extensions.json
  .vscode/settings.json
  README.md
  __tests__/data/dataFormats.ts
  __tests__/data/dataTransformations.ts
  __tests__/filterData.test.ts
  __tests__/transformData.test.ts
  __tests__/transformFormat.test.ts
  docs/configuration/configuration.en.md
  docs/development.en.md
  docs/features/visualizations.en.md
  jest.config.ts
  mkdocs.yml
  next.config.mjs
  package-lock.json
  package.json
  src/app/[locale]/[...not-found]/page.tsx
  src/app/[locale]/layout.tsx
  src/app/[locale]/not-found.tsx
  src/app/[locale]/page.tsx
  src/app/[locale]/resource/[resourceId]/page.tsx
  src/app/layout.tsx
  src/app/not-found.tsx
  src/app/page.tsx
  src/components/visualization/layout/ChartTableWrapper.tsx
  src/components/visualization/layout/Visualization.tsx
  src/components/visualization/map/GeoMap.tsx
  src/components/visualization/map/ResetView.tsx
  src/filter.ts
  src/messages/de.json
  src/messages/en.json
  src/middleware.ts
  src/prefix.ts
  src/types/configuration.d.ts
Labels: enhancement

#68 feat: Add favicon
  public/next.svg
  public/vercel.svg
  src/app/[locale]/layout.tsx
  src/app/[locale]/page.module.css
  src/app/[locale]/page.tsx
  src/app/favicon.ico
  src/app/globals.css
  src/app/icon.ico
  src/messages/de.json
  src/messages/en.json
Labels: enhancement

#72 feat: Select visualization by query parameter
  src/components/visualization/layout/ChartTableWrapper.tsx
Labels: enhancement

#71 feat: make bar chart axes selectable
  data-source.config.yml
  src/colors.ts
  src/components/visualization/BarChart.tsx
  src/components/visualization/bar-chart/AxisSelector.tsx
  src/components/visualization/bar-chart/BarChart.tsx
  src/components/visualization/layout/ChartTableWrapper.tsx
  src/components/visualization/map/GeoMap.tsx
  src/messages/de.json
  src/messages/en.json
  src/types/configuration.d.ts
  src/types/visualization.d.ts
  src/utils/maputils.ts
Labels: enhancement

#82 feat: Application theming and Karlsruhe theme
  .vscode/settings.json
  __tests__/units/colors.test.ts
  data-source.config.yml
  docs/configuration/configuration.en.md
  src/app/[locale]/layout.tsx
  src/app/[locale]/resource/[resourceId]/page.tsx
  src/colors.ts
  src/components/LocaleSwitcher.tsx
  src/components/visualization/Table.tsx
  src/components/visualization/bar-chart/AxisSelector.tsx
  src/components/visualization/bar-chart/BarChart.tsx
  src/components/visualization/chart-table-filter/ChartTableFilterBody.tsx
  src/components/visualization/chart-table-filter/ChartTableFilterHeader.tsx
  src/components/visualization/chart-table-filter/ClearableInputGroup.tsx
  src/components/visualization/map/GeoMap.tsx
  src/components/visualization/map/ResetView.tsx
  src/configuration.ts
  src/themes/globals.scss
  src/themes/theme.karlsruhe.scss
  src/types/configuration.d.ts
  tsconfig.json
Labels: documentation, enhancement

#84 feat: add label for map features to config, refactor legend component
  __tests__/components/legend.test.tsx
  __tests__/data/mapComponentData.ts
  data-source.config.yml
  src/components/visualization/layout/Visualization.tsx
  src/components/visualization/map/GeoMap.tsx
  src/components/visualization/map/Legend.tsx
  src/components/visualization/map/ResetView.tsx
  src/components/visualization/map/mapstyles.module.css
  src/messages/de.json
  src/messages/en.json
  src/types/configuration.d.ts
Labels: enhancement

#87 feat: Implement option for setting default filters in configuration file
  __tests__/components/chartTableFilterHeader.test.tsx
  data-source.config.yml
  src/components/visualization/chart-table-filter/ChartTableFilter.tsx
  src/schema.ts
Labels: enhancement

#89 fix: account for german number formats in chart
  __tests__/data/dataFormats.ts
  __tests__/data/dataTransformations.ts
  __tests__/data/resources.ts
  __tests__/units/transformData.test.ts
  data-source.config.yml
  src/components/visualization/bar-chart/BarChart.tsx
  src/components/visualization/layout/ChartTableWrapper.tsx
  src/schema.ts
  src/transform.ts
  src/types/visualization.d.ts
Labels: bug

#104 feat: Allow splitting configuration into multiple files
  config/data-source.app.config.yml
  docs/configuration/configuration.en.md
  src/app/[locale]/layout.tsx
  src/app/[locale]/resource/[resourceId]/page.tsx
  src/components/error-handling/ErrorComponent.tsx
  src/configuration.ts
  src/messages/de.json
  src/messages/en.json
Labels: documentation, enhancement

#95 feat: Streamline transformations and minor component improvements
  __tests__/components/ChartTableFilterBody.test.tsx
  __tests__/components/Table.test.tsx
  __tests__/data/dataFormats.ts
  __tests__/data/dataTransformations.ts
  __tests__/data/resources.ts
  __tests__/units/filterData.test.ts
  __tests__/units/transformData.test.ts
  __tests__/units/transformFormat.test.ts
  src/app/[locale]/resource/[resourceId]/page.tsx
  src/components/error-handling/ErrorComponent.tsx
  src/components/visualization/EmbeddedViewer.tsx
  src/components/visualization/Table.tsx
  src/components/visualization/bar-chart/BarChart.tsx
  src/components/visualization/chart-table-filter/ChartTableFilter.tsx
  src/components/visualization/chart-table-filter/ChartTableFilterBody.tsx
  src/components/visualization/chart-table-filter/ChartTableFilterHeader.tsx
  src/components/visualization/chart-table-filter/ClearableInputGroup.tsx
  src/components/visualization/chart-table-filter/CurrentFilters.tsx
  src/components/visualization/layout/ChartTableWrapper.tsx
  src/components/visualization/layout/Visualization.tsx
  src/components/visualization/map/GeoMap.tsx
  src/configuration.ts
  src/filter.ts
  src/schema.ts
  src/schemas/configuration-schema.ts
  src/schemas/data-schema.ts
  src/transform.ts
  src/transformations/transformData.ts
  src/transformations/transformFormat.ts
  src/transformations/transformType.ts
  src/types/visualization.d.ts
Labels: enhancement
