Repository stadt-karlsruhe/open-data-dashboard, pull requests merged in 2024-06, with the labels that each got.

#106 feat: Standardize configuration options across data types
  __tests__/components/BarChart.test.tsx
  __tests__/components/GeoMap.test.tsx
  __tests__/components/Table.test.tsx
  __tests__/components/Visualization.test.tsx
  __tests__/data/dataFormats.ts
  __tests__/data/dataTransformations.ts
  __tests__/data/resources.ts
  __tests__/units/transformData.test.ts
  __tests__/units/transformFormat.test.ts
  config/data-source.app.config.yml
  jest.setup.tsx
  src/app/[locale]/resource/[resourceId]/page.tsx
  src/components/visualization/bar-chart/BarChart.tsx
  src/components/visualization/chart-table-filter/ChartTableFilter.tsx
  src/components/visualization/layout/ChartTableWrapper.tsx
  src/components/visualization/layout/Visualization.tsx
  src/components/visualization/map/GeoMap.tsx
  src/configuration.ts
  src/messages/de.json
  src/messages/en.json
  src/schemas/configuration-schema.ts
  src/schemas/data-schema.ts
  src/transformations/transformData.ts
  src/transformations/transformFormat.ts
  src/transformations/transformType.ts
Labels: enhancement

#111 ci: Configure Lighthouse
  .github/workflows/lighthouse.yml
  .gitignore
  .lighthouserc.yml
Labels: enhancement

#108 feat: add header component
  .vscode/settings.json
  package-lock.json
  src/app/[locale]/(main)/home/page.tsx
  src/app/[locale]/(main)/layout.tsx
  src/app/[locale]/(main)/page.tsx
  src/components/header/Header.tsx
  src/messages/de.json
  src/messages/en.json
  src/public/Logo_Digital_Karlsruhe-rechts_rgb.svg
  src/public/Logo_Digital_Karlsruhe-rechts_rgb_small.svg
  src/themes/globals.scss
Labels: enhancement

#122 feat: Validate configuration files using Jest
  .github/workflows/config-validation.yml
  __tests__/config-validation/configuration.test.ts
  __tests__/config-validation/configurationMatcher.ts
  package-lock.json
  package.json
  src/app/[locale]/(embedded)/resource/[resourceId]/page.tsx
  src/app/[locale]/(main)/view/[viewId]/page.tsx
  src/messages/de.json
  src/messages/en.json
  src/schemas/configuration-schema.ts
Labels: enhancement, github_actions

#125 feat: Search for datasets
  .eslintrc.yml
  .vscode/settings.json
  config/data-source.app.config.yml
  package-lock.json
  package.json
  src/app/[locale]/(main)/layout.tsx
  src/components/header/Header.tsx
  src/components/header/LocaleSwitcher.tsx
  src/components/navigation/Navigation.tsx
  src/components/navigation/NavigationContent.tsx
  src/components/resource-details/ResourceDetailsControls.tsx
  src/components/search/Search.tsx
  src/messages/de.json
  src/messages/en.json
  src/themes/globals.scss
  src/themes/theme.karlsruhe.scss
Labels: enhancement

#128 feat: Implement homepage
  .lighthouserc.yml
  .vscode/settings.json
  __tests__/config-validation/configurationMatcher.ts
  __tests__/data/resources.ts
  config/data-source.app.config.yml
  next.config.mjs
  src/app/[locale]/(embedded)/resource/[resourceId]/page.tsx
  src/app/[locale]/(main)/home/page.tsx
  src/app/[locale]/(main)/layout.tsx
  src/components/dashboard/DashboardContent.tsx
  src/components/header/Header.tsx
  src/components/header/LocaleSwitcher.tsx
  src/components/navigation/Navigation.tsx
  src/components/navigation/NavigationContent.tsx
  src/components/resource-details/ResourceDetails.tsx
  src/components/resource-details/ResourceDetailsControls.tsx
  src/components/search/Search.tsx
  src/components/search/SearchResult.tsx
  src/components/visualization/EmbeddedViewer.tsx
  src/components/visualization/chart-table-filter/ChartTableFilterBody.tsx
  src/components/visualization/chart-table-filter/ClearableInputGroup.tsx
  src/components/visualization/map/GeoMap.tsx
  src/components/visualization/map/ResetView.tsx
  src/icons.ts
  src/schemas/configuration-schema.ts
Labels: enhancement

#146 feat: Make dashboards and categories searchable, prepare dashboard implementation
  .lighthouserc.yml
  __tests__/components/visualization/chart-table-filter/ChartTableFilterBody.test.tsx
  __tests__/components/visualization/chart-table-filter/ChartTableFilterHeader.test.tsx
  src/app/[locale]/(main)/dashboard/[dashboardNameAndId]/page.tsx
  src/app/[locale]/(main)/home/page.tsx
  src/app/[locale]/(main)/overview/dashboards/page.tsx
  src/app/[locale]/(main)/overview/resources/[categoryName]/[[...subcategoryName]]/page.tsx
  src/app/[locale]/(main)/overview/resources/page.tsx
  src/app/[locale]/(main)/resource/[resourceNameAndId]/page.tsx
  src/app/robots.ts
  src/components/dashboard-resource/DashboardContent.tsx
  src/components/dashboard-resource/DashboardResourceControls.tsx
  src/components/dashboard-resource/EmbedModal.tsx
  src/components/dashboard-resource/ResourceDetails.tsx
  src/components/navigation/NavigationContent.tsx
  src/components/overview/Overview.tsx
  src/components/resource-details/ResourceDetailsControls.tsx
  src/components/search/Search.tsx
  src/components/search/SearchResult.tsx
  src/components/visualization/chart-table-filter/ChartTableFilter.tsx
  src/components/visualization/chart-table-filter/ChartTableFilterBody.tsx
  src/components/visualization/chart-table-filter/ChartTableFilterHeader.tsx
  src/messages/de.json
  src/messages/en.json
  src/themes/theme.karlsruhe.scss
  src/types/data.d.ts
  src/utils/mapUtils.ts
Labels: enhancement

#147 feat: add LRUCache to categories
  package-lock.json
  package.json
  src/app/[locale]/(main)/overview/resources/[categoryName]/[[...subcategoryName]]/page.tsx
  src/utils/mapUtils.ts
Labels: enhancement

#149 feat: setup cypress e2e tests
  .github/workflows/cypress.yml
  __tests__/cypress/.eslintrc.yml
  __tests__/cypress/e2e/spec.home.cy.ts
  __tests__/cypress/support/commands.ts
  __tests__/cypress/support/e2e.ts
  cypress.config.ts
  package-lock.json
  package.json
Labels: enhancement

#150 feat: Extend GeoMap component to support polygons and lines
  .lighthouserc.yml
  .vscode/settings.json
  __tests__/components/visualization/map/GeoMap.test.tsx
  config/data-source.app.config.yml
  package-lock.json
  package.json
  src/components/visualization/Visualization.tsx
  src/components/visualization/map/GeoMap.tsx
  src/components/visualization/map/Legend.tsx
  src/schemas/configurationSchema.ts
  src/schemas/dataSchema.ts
  src/transformations/transformType.ts
Labels: enhancement

#167 feat: add cypress tests for several pages
  .github/workflows/cypress.yml
  .vscode/settings.json
  __tests__/cypress/.eslintrc.yml
  __tests__/cypress/config/data-source.app.config.yml
  __tests__/cypress/e2e/spec.footer.cy.ts
  __tests__/cypress/e2e/spec.header.cy.ts
  __tests__/cypress/e2e/spec.home.cy.ts
  __tests__/cypress/e2e/spec.navigation.cy.ts
  __tests__/cypress/e2e/spec.overview.cy.ts
  __tests__/cypress/e2e/spec.resourceDetail.cy.ts
  docs/cicd-testing/cd.en.md
  docs/cicd-testing/ci.en.md
  docs/cicd-testing/testing.en.md
  docs/configuration/index.en.md
  mkdocs.yml
  package-lock.json
  package.json
  src/components/dashboard-resource/DashboardResourceControls.tsx
  src/components/dashboard-resource/EmbedModal.tsx
  src/components/footer/Footer.tsx
  src/components/footer/LocaleSwitcher.tsx
  src/components/header/Header.tsx
  src/components/layout/ChartTableWrapper.tsx
  src/components/layout/PageWrapper.tsx
  src/components/navigation/Navigation.tsx
  src/components/navigation/NavigationContent.tsx
  src/components/visualization/bar-chart/BarChart.tsx
  src/components/visualization/chart-table-filter/ChartTableFilterBody.tsx
  src/components/visualization/chart-table-filter/ChartTableFilterHeader.tsx
  src/components/visualization/chart-table-filter/ClearableInputGroup.tsx
  src/configuration.ts
Labels: enhancement

#164 docs: Beautify README
  README.md
Labels: documentation

#176 fix: Broken resources and minor bugs
  __tests__/cypress/config/gesellschaft.app.config.yml
  __tests__/cypress/config/pois.app.config.yml
  config/gesellschaft.app.config.yml
  config/pois.app.config.yml
  src/components/search/Search.tsx
  src/components/visualization/map/Legend.tsx
  src/schemas/dataSchema.ts
  src/schemas/validate.ts
  src/transformations/transformType.ts
  src/utils/colors.ts
Labels: bug

#180 feat: descriptions for config
  config/kategorien.app.config.yml
  config/pois.app.config.yml
Labels: enhancement

#181 feat: add cypress tests for all missing pages
  .vscode/settings.json
  __tests__/cypress/.eslintrc.yml
  __tests__/cypress/config/pois.app.config.yml
  __tests__/cypress/e2e/cypressConstants.ts
  __tests__/cypress/e2e/spec.dashboard.cy.ts
  __tests__/cypress/e2e/spec.embed.cy.ts
  __tests__/cypress/e2e/spec.header.cy.ts
  __tests__/cypress/e2e/spec.home.cy.ts
  __tests__/cypress/e2e/spec.navigation.cy.ts
  __tests__/cypress/e2e/spec.notFound.cy.ts
  __tests__/cypress/e2e/spec.overview.cy.ts
  __tests__/cypress/e2e/spec.resourceDetail.cy.ts
  src/components/dashboard-resource/dashboard/CarouselContent.tsx
  src/components/dashboard-resource/dashboard/ResourceContent.tsx
  src/components/error-handling/ErrorComponent.tsx
  src/components/visualization/map/Legend.tsx
  src/components/visualization/map/ResetView.tsx
Labels: enhancement
